### PR TITLE
fix: upgrade depdencies to latest versions, require NodeJS >= 18

### LINKED ISSUE #250: Please update to latest @ocktokit/auth because of jsonwebtoken
The `jsonwebtoken` package in version 8.5.1 has a severe vulnerability, fixed in version 9.0.0, and in @octokit/auth 4.0.8 (via `universal-github-app-jwt`).

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: require NodeJS >= 18

Fixes #259, Fixes #258, Fixes #257, Fixes #251, Fixes #250, Fixes #248, Fixes #236, Fixes #233

### CODE REVIEW

**Comment by Uzlopak** [comment]
Oh, @wolfy1339 
I didnt see your PR last night. I will close my PR, 😁

File: src/index.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
-import { auth } from "./auth";
-import { getState } from "./get-state";
-import { StrategyOptions, State } from "./types";
-import { VERSION } from "./version";
+import { auth } from "./auth.js";
```
Comment (Uzlopak) [inline src/index.ts:1]: Why do you import the .js file?

**Comment by Uzlopak** [comment]
@wolfy1339 
Maybe you want to compare your pr with mine and adapt some differences?

File: src/index.ts (hunk 1 above)
Comment (wolfy1339) [reply src/index.ts:1]: It's so the output has a proper ESM import.
You have to have a proper full relative path in imports

Comment (Uzlopak) [reply src/index.ts:1]: I didnt need to do that in my PR. Doesnt typescript take care of that + we bundle anyway?

Comment (wolfy1339) [reply src/index.ts:1]: The imports will work fine in CJS, but not in ESM output.
If you try to import the `dist-src` it will fail because the imports aren't proper

TypeScript doesn't add any file extensions to the imports.

Comment (Uzlopak) [reply src/index.ts:1]: But if it is bundled we wont import that files?

**Comment by wolfy1339** [comment]
@gr2m Can you review this when you get the time? It's needed for the Probot upgrade

**Review by gr2m — APPROVED** [review]
looks great 👍🏼

**Comment by wolfy1339** [comment]
The coverage seems to have dropped, not sure why.

**Comment by wolfy1339** [comment]
Fixed all the test failures. This is now good to go

**Review by gr2m — APPROVED** [review]
Outstanding work, thank you!!
